# General
spring.application.name=portfolio
server.servlet.context-path=/api
# Database
spring.datasource.url=jdbc:postgresql://localhost:5432/stock_portfolio
spring.datasource.username=postgres
spring.datasource.password=123456
spring.datasource.driver-class-name=org.postgresql.Driver
# JPA
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
# JWT
jwt.secret=${JWT_SECRET:+K7sDeT3fUoyB2CvEJhg5DB+udkqNP3AFtqiHCqsUcI=}
jwt.access-token-expiration=900000
jwt.refresh-token-expiration=604800000
# Finnhub
finnhub.api.key=${FINNHUB_API_KEY:YOUR_API_KEY}
finnhub.api.base-url=https://finnhub.io/api/v1