# General
spring.application.name=portfolio
server.servlet.context-path=/api
# Database
spring.datasource.url=jdbc:postgresql://localhost:5432/stock_portfolio
spring.datasource.username=postgres
spring.datasource.password=123456
spring.datasource.driver-class-name=org.postgresql.Driver
# JPA
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect