apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service
  namespace: portfolio
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-service
  template:
    metadata:
      labels:
        app: auth-service
    spec:
      containers:
        - name: auth-service
          image: auth-service:local
          imagePullPolicy: Never
          ports:
            - containerPort: 8081
          envFrom:
            - configMapRef:
                name: app-config
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://postgres:5432/auth_service_db
            - name: WALLET_SERVICE_URL
              value: http://wallet-service:8082/api
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: JWT_SECRET
---
apiVersion: v1
kind: Service
metadata:
  name: auth-service
  namespace: portfolio
spec:
  type: NodePort
  selector:
    app: auth-service
  ports:
    - port: 8081
      targetPort: 8081
      nodePort: 30081