apiVersion: apps/v1
kind: Deployment
metadata:
  name: portfolio-service
  namespace: portfolio
spec:
  replicas: 1
  selector:
    matchLabels:
      app: portfolio-service
  template:
    metadata:
      labels:
        app: portfolio-service
    spec:
      containers:
        - name: portfolio-service
          image: portfolio-service:local
          imagePullPolicy: Never
          ports:
            - containerPort: 8084
          envFrom:
            - configMapRef:
                name: app-config
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://postgres:5432/portfolio_service_db
            - name: STOCK_SERVICE_URL
              value: http://stock-service:8083/api
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: JWT_SECRET
---
apiVersion: v1
kind: Service
metadata:
  name: portfolio-service
  namespace: portfolio
spec:
  type: NodePort
  selector:
    app: portfolio-service
  ports:
    - port: 8084
      targetPort: 8084
      nodePort: 30084