apiVersion: apps/v1
kind: Deployment
metadata:
  name: wallet-service
  namespace: portfolio
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wallet-service
  template:
    metadata:
      labels:
        app: wallet-service
    spec:
      containers:
        - name: wallet-service
          image: wallet-service:local
          imagePullPolicy: Never
          ports:
            - containerPort: 8082
          envFrom:
            - configMapRef:
                name: app-config
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://postgres:5432/wallet_service_db
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: JWT_SECRET
---
apiVersion: v1
kind: Service
metadata:
  name: wallet-service
  namespace: portfolio
spec:
  type: NodePort
  selector:
    app: wallet-service
  ports:
    - port: 8082
      targetPort: 8082
      nodePort: 30082