# General
spring.application.name=portfolio-service
server.port=8084
server.servlet.context-path=/api
# Database
spring.datasource.url=jdbc:postgresql://localhost:5432/stock_portfolio
spring.datasource.username=postgres
spring.datasource.password=123456
spring.datasource.driver-class-name=org.postgresql.Driver
# Kafka
spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JacksonJsonSerializer
# JPA
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
# JWT
jwt.secret=${JWT_SECRET:+K7sDeT3fUoyB2CvEJhg5DB+udkqNP3AFtqiHCqsUcI=}
jwt.access-token-expiration=900000
jwt.refresh-token-expiration=604800000
# Actuator
management.endpoints.web.exposure.include=health,loggers,metrics
# Client
stock-service.url=http://localhost:8083/api
